name: ShawnRPhotography
favicon: null
layout_spectrum: 0.8245399403385818
typography_spectrum: 0.8303901045583189
title: Shawn R Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.8239474736619741
  lightness: 0.16192376078106463
  saturation: 0.8296497208066285
  rhythmicContrast: 0.9768314687535167
purpose: []
